package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"Katara/graph/model"
	"context"
)

// GetAnimeByID is the resolver for the getAnimeByID field.
func (r *queryResolver) GetAnimeByID(ctx context.Context, aniListID int32) (*model.Anime, error) {
	animeByID, err := r.AnimeService.GetAnimeByID(ctx, int(aniListID))

	if err != nil {
		return nil, err
	}

	anime := toGraphqlAnime(animeByID)

	return anime, nil
}

// GetAnimeWithFilters is the resolver for the getAnimeWithFilters field.
func (r *queryResolver) GetAnimeWithFilters(ctx context.Context, animeFilter model.AnimeFilter) ([]*model.Anime, error) {
	animes, err := r.AnimeService.GetAnimeWithFilters(ctx, toAnimeFilter(animeFilter))
	if err != nil {
		return nil, err
	}

	result := make([]*model.Anime, len(animes))
	for i, a := range animes {
		result[i] = toGraphqlAnime(&a)
	}
	return result, nil
}
