package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"Katara/graph/model"
	"context"
	"fmt"
)

// AddList is the resolver for the addList field.
func (r *mutationResolver) AddList(ctx context.Context, input model.AddListInput) (bool, error) {
	panic("not implemented")
}

// UpdateList is the resolver for the updateList field.
func (r *mutationResolver) UpdateList(ctx context.Context, list *model.AddListInput) (bool, error) {
	panic("not implemented")
}

// DeleteList is the resolver for the deleteList field.
func (r *mutationResolver) DeleteList(ctx context.Context, anilistID *int32) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteList - deleteList"))
}

// GetAllLists is the resolver for the getAllLists field.
func (r *queryResolver) GetAllLists(ctx context.Context, mediaListStatus []*model.MediaListStatus) ([]*model.List, error) {
	panic(fmt.Errorf("not implemented: GetAllLists - getAllLists"))
}

// GetListByStatus is the resolver for the getListByStatus field.
func (r *queryResolver) GetListByStatus(ctx context.Context, mediaListStatus *model.MediaListStatus) ([]*model.List, error) {
	panic(fmt.Errorf("not implemented: GetListByStatus - getListByStatus"))
}
