package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"Katara/graph/model"
	"context"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, loginInput model.LoginInput) (*model.User, error) {
	usr, err := r.UserService.Login(ctx, loginInput.Email, loginInput.Password)

	if err != nil {
		return nil, err
	}

	User := toGraphqlUser(usr)

	return User, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, registerInput model.RegisterInput) (*model.User, error) {
	usr, err := r.UserService.Register(ctx, registerInput.Email, registerInput.Name, registerInput.Password)

	if err != nil {
		return nil, err
	}

	User := toGraphqlUser(usr)

	return User, nil
}

// UpdateEmail is the resolver for the updateEmail field.
func (r *mutationResolver) UpdateEmail(ctx context.Context, newEmail string) (*model.User, error) {
	var mongoID bson.ObjectID
	updEmail, err := r.UserService.UpdateEmail(ctx, mongoID, newEmail)

	if err != nil {
		return nil, err
	}

	userWithUpdatedEmail := toGraphqlUser(updEmail)

	return userWithUpdatedEmail, nil
}

// UpdatePassword is the resolver for the updatePassword field.
func (r *mutationResolver) UpdatePassword(ctx context.Context, oldPassword string, newPassword string) (*model.User, error) {
	var mongoID bson.ObjectID
	updPass, err := r.UserService.UpdatePassword(ctx, mongoID, oldPassword, newPassword)

	if err != nil {
		return nil, err
	}

	userWithUpdatedPassword := toGraphqlUser(updPass)

	return userWithUpdatedPassword, nil
}

// UpdateAvatar is the resolver for the updateAvatar field.
func (r *mutationResolver) UpdateAvatar(ctx context.Context, newAvatar model.UserAvatarInput) (*model.User, error) {
	var mongoID bson.ObjectID
	updAvatar, err := r.UserService.UpdateAvatar(ctx, mongoID, fromGraphqlUserAvatar(&newAvatar))

	if err != nil {
		return nil, err
	}

	userWithUpdatedAvatar := toGraphqlUser(updAvatar)

	return userWithUpdatedAvatar, nil
}

// UpdateBannerImage is the resolver for the updateBannerImage field.
func (r *mutationResolver) UpdateBannerImage(ctx context.Context, newBannerImage string) (*model.User, error) {
	var mongoID bson.ObjectID
	updBannerImage, err := r.UserService.UpdateBannerImage(ctx, mongoID, newBannerImage)

	if err != nil {
		return nil, err
	}

	userWithUpdatedBannerImage := toGraphqlUser(updBannerImage)

	return userWithUpdatedBannerImage, nil
}

// UpdateAbout is the resolver for the updateAbout field.
func (r *mutationResolver) UpdateAbout(ctx context.Context, newAbout string) (*model.User, error) {
	var mongoID bson.ObjectID
	updAbout, err := r.UserService.UpdateAbout(ctx, mongoID, newAbout)

	if err != nil {
		return nil, err
	}

	userWithUpdatedAbout := toGraphqlUser(updAbout)

	return userWithUpdatedAbout, nil
}
