// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddListInput struct {
	AniListID  int32           `json:"aniListID"`
	Status     MediaListStatus `json:"status"`
	Score      *float64        `json:"score,omitempty"`
	Progress   *int32          `json:"progress,omitempty"`
	Repeat     *int32          `json:"repeat,omitempty"`
	Priority   *int32          `json:"priority,omitempty"`
	Private    bool            `json:"private"`
	Notes      *string         `json:"notes,omitempty"`
	StartedAt  *FuzzyDateInput `json:"startedAt,omitempty"`
	FinishedAt *FuzzyDateInput `json:"finishedAt,omitempty"`
}

type Anime struct {
	AniListID    int32            `json:"aniListID"`
	MongoID      string           `json:"mongoID"`
	Title        *MediaTitle      `json:"title,omitempty"`
	CoverImage   *MediaCoverImage `json:"coverImage,omitempty"`
	Format       *MediaFormat     `json:"format,omitempty"`
	Status       *MediaStatus     `json:"status,omitempty"`
	Episodes     *int32           `json:"episodes,omitempty"`
	Genres       []string         `json:"genres,omitempty"`
	AverageScore *int32           `json:"averageScore,omitempty"`
	Popularity   *int32           `json:"popularity,omitempty"`
	Trending     *int32           `json:"trending,omitempty"`
	Description  *string          `json:"description,omitempty"`
	Trailer      *MediaTrailer    `json:"trailer,omitempty"`
	Studios      []*Studio        `json:"studios,omitempty"`
	Season       *MediaSeason     `json:"season,omitempty"`
	SeasonYear   *int32           `json:"seasonYear,omitempty"`
	SeasonInt    *int32           `json:"seasonInt,omitempty"`
	Tags         []*Mediatag      `json:"tags,omitempty"`
	SyncedAt     *time.Time       `json:"syncedAt,omitempty"`
}

type AnimeFilter struct {
	AnilistID *int32       `json:"AnilistID,omitempty"`
	Sort      *MediaSort   `json:"Sort,omitempty"`
	Status    *MediaStatus `json:"Status,omitempty"`
	Season    *MediaSeason `json:"Season,omitempty"`
	Format    *MediaFormat `json:"Format,omitempty"`
	Genre     []*string    `json:"Genre,omitempty"`
	Year      *int32       `json:"Year,omitempty"`
	Page      *int32       `json:"Page,omitempty"`
	PerPage   *int32       `json:"PerPage,omitempty"`
}

type FuzzyDate struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
	Day   int32 `json:"day"`
}

type FuzzyDateInput struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
	Day   int32 `json:"day"`
}

type List struct {
	AniListID  int32           `json:"aniListID"`
	Status     MediaListStatus `json:"status"`
	Score      *float64        `json:"score,omitempty"`
	Progress   *int32          `json:"progress,omitempty"`
	Repeat     *int32          `json:"repeat,omitempty"`
	Priority   *int32          `json:"priority,omitempty"`
	Private    bool            `json:"private"`
	Notes      *string         `json:"notes,omitempty"`
	StartedAt  *FuzzyDate      `json:"startedAt,omitempty"`
	FinishedAt *FuzzyDate      `json:"finishedAt,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LogoutResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type MediaCoverImage struct {
	ExtraLarge string `json:"extraLarge"`
	Large      string `json:"large"`
	Medium     string `json:"medium"`
	Color      string `json:"color"`
}

type MediaTitle struct {
	Romaji        string `json:"romaji"`
	English       string `json:"english"`
	Native        string `json:"native"`
	UserPreferred string `json:"userPreferred"`
}

type MediaTrailer struct {
	ID        string `json:"id"`
	Site      string `json:"site"`
	Thumbnail string `json:"thumbnail"`
}

type Mediatag struct {
	ID               int32  `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Category         string `json:"category"`
	Rank             int32  `json:"rank"`
	IsGeneralSpoiler bool   `json:"isGeneralSpoiler"`
	IsMediaSpoiler   bool   `json:"isMediaSpoiler"`
	IsAdult          bool   `json:"isAdult"`
	UserID           int32  `json:"userID"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Studio struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateListInput struct {
	Status     MediaListStatus `json:"status"`
	Score      *float64        `json:"score,omitempty"`
	Progress   *int32          `json:"progress,omitempty"`
	Repeat     *int32          `json:"repeat,omitempty"`
	Priority   *int32          `json:"priority,omitempty"`
	Private    *bool           `json:"private,omitempty"`
	Notes      *string         `json:"notes,omitempty"`
	StartedAt  *FuzzyDateInput `json:"startedAt,omitempty"`
	FinishedAt *FuzzyDateInput `json:"finishedAt,omitempty"`
}

type User struct {
	Name        string      `json:"name"`
	Email       string      `json:"email"`
	About       *string     `json:"about,omitempty"`
	Avatar      *UserAvatar `json:"avatar,omitempty"`
	BannerImage *string     `json:"bannerImage,omitempty"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   time.Time   `json:"updatedAt"`
}

type UserAvatar struct {
	Large  *string `json:"large,omitempty"`
	Medium *string `json:"medium,omitempty"`
}

type UserAvatarInput struct {
	Large  *string `json:"large,omitempty"`
	Medium *string `json:"medium,omitempty"`
}

type MediaFormat string

const (
	MediaFormatTv      MediaFormat = "TV"
	MediaFormatTvShort MediaFormat = "TV_SHORT"
	MediaFormatMovie   MediaFormat = "MOVIE"
	MediaFormatSpecial MediaFormat = "SPECIAL"
	MediaFormatOva     MediaFormat = "OVA"
	MediaFormatOna     MediaFormat = "ONA"
	MediaFormatMusic   MediaFormat = "MUSIC"
	MediaFormatManga   MediaFormat = "MANGA"
	MediaFormatNovel   MediaFormat = "NOVEL"
	MediaFormatOneShot MediaFormat = "ONE_SHOT"
)

var AllMediaFormat = []MediaFormat{
	MediaFormatTv,
	MediaFormatTvShort,
	MediaFormatMovie,
	MediaFormatSpecial,
	MediaFormatOva,
	MediaFormatOna,
	MediaFormatMusic,
	MediaFormatManga,
	MediaFormatNovel,
	MediaFormatOneShot,
}

func (e MediaFormat) IsValid() bool {
	switch e {
	case MediaFormatTv, MediaFormatTvShort, MediaFormatMovie, MediaFormatSpecial, MediaFormatOva, MediaFormatOna, MediaFormatMusic, MediaFormatManga, MediaFormatNovel, MediaFormatOneShot:
		return true
	}
	return false
}

func (e MediaFormat) String() string {
	return string(e)
}

func (e *MediaFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaFormat", str)
	}
	return nil
}

func (e MediaFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MediaListStatus string

const (
	MediaListStatusCurrent   MediaListStatus = "CURRENT"
	MediaListStatusPlanning  MediaListStatus = "PLANNING"
	MediaListStatusCompleted MediaListStatus = "COMPLETED"
	MediaListStatusDropped   MediaListStatus = "DROPPED"
	MediaListStatusPaused    MediaListStatus = "PAUSED"
	MediaListStatusRepeating MediaListStatus = "REPEATING"
)

var AllMediaListStatus = []MediaListStatus{
	MediaListStatusCurrent,
	MediaListStatusPlanning,
	MediaListStatusCompleted,
	MediaListStatusDropped,
	MediaListStatusPaused,
	MediaListStatusRepeating,
}

func (e MediaListStatus) IsValid() bool {
	switch e {
	case MediaListStatusCurrent, MediaListStatusPlanning, MediaListStatusCompleted, MediaListStatusDropped, MediaListStatusPaused, MediaListStatusRepeating:
		return true
	}
	return false
}

func (e MediaListStatus) String() string {
	return string(e)
}

func (e *MediaListStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaListStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaListStatus", str)
	}
	return nil
}

func (e MediaListStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaListStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaListStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MediaSeason string

const (
	MediaSeasonWinter MediaSeason = "WINTER"
	MediaSeasonSpring MediaSeason = "SPRING"
	MediaSeasonSummer MediaSeason = "SUMMER"
	MediaSeasonFall   MediaSeason = "FALL"
)

var AllMediaSeason = []MediaSeason{
	MediaSeasonWinter,
	MediaSeasonSpring,
	MediaSeasonSummer,
	MediaSeasonFall,
}

func (e MediaSeason) IsValid() bool {
	switch e {
	case MediaSeasonWinter, MediaSeasonSpring, MediaSeasonSummer, MediaSeasonFall:
		return true
	}
	return false
}

func (e MediaSeason) String() string {
	return string(e)
}

func (e *MediaSeason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaSeason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaSeason", str)
	}
	return nil
}

func (e MediaSeason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaSeason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaSeason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MediaSort string

const (
	MediaSortTitleRomaji      MediaSort = "TITLE_ROMAJI"
	MediaSortTitleRomajiDesc  MediaSort = "TITLE_ROMAJI_DESC"
	MediaSortTitleEnglish     MediaSort = "TITLE_ENGLISH"
	MediaSortTitleEnglishDesc MediaSort = "TITLE_ENGLISH_DESC"
	MediaSortTitleNative      MediaSort = "TITLE_NATIVE"
	MediaSortTitleNativeDesc  MediaSort = "TITLE_NATIVE_DESC"
	MediaSortFormat           MediaSort = "FORMAT"
	MediaSortFormatDesc       MediaSort = "FORMAT_DESC"
	MediaSortStartDate        MediaSort = "START_DATE"
	MediaSortStartDateDesc    MediaSort = "START_DATE_DESC"
	MediaSortEndDate          MediaSort = "END_DATE"
	MediaSortEndDateDesc      MediaSort = "END_DATE_DESC"
	MediaSortScore            MediaSort = "SCORE"
	MediaSortScoreDesc        MediaSort = "SCORE_DESC"
	MediaSortPopularity       MediaSort = "POPULARITY"
	MediaSortPopularityDesc   MediaSort = "POPULARITY_DESC"
	MediaSortTrending         MediaSort = "TRENDING"
	MediaSortTrendingDesc     MediaSort = "TRENDING_DESC"
	MediaSortEpisodes         MediaSort = "EPISODES"
	MediaSortEpisodesDesc     MediaSort = "EPISODES_DESC"
	MediaSortDuration         MediaSort = "DURATION"
	MediaSortDurationDesc     MediaSort = "DURATION_DESC"
	MediaSortStatus           MediaSort = "STATUS"
	MediaSortStatusDesc       MediaSort = "STATUS_DESC"
	MediaSortUpdatedAt        MediaSort = "UPDATED_AT"
	MediaSortUpdatedAtDesc    MediaSort = "UPDATED_AT_DESC"
	MediaSortSearchMatch      MediaSort = "SEARCH_MATCH"
)

var AllMediaSort = []MediaSort{
	MediaSortTitleRomaji,
	MediaSortTitleRomajiDesc,
	MediaSortTitleEnglish,
	MediaSortTitleEnglishDesc,
	MediaSortTitleNative,
	MediaSortTitleNativeDesc,
	MediaSortFormat,
	MediaSortFormatDesc,
	MediaSortStartDate,
	MediaSortStartDateDesc,
	MediaSortEndDate,
	MediaSortEndDateDesc,
	MediaSortScore,
	MediaSortScoreDesc,
	MediaSortPopularity,
	MediaSortPopularityDesc,
	MediaSortTrending,
	MediaSortTrendingDesc,
	MediaSortEpisodes,
	MediaSortEpisodesDesc,
	MediaSortDuration,
	MediaSortDurationDesc,
	MediaSortStatus,
	MediaSortStatusDesc,
	MediaSortUpdatedAt,
	MediaSortUpdatedAtDesc,
	MediaSortSearchMatch,
}

func (e MediaSort) IsValid() bool {
	switch e {
	case MediaSortTitleRomaji, MediaSortTitleRomajiDesc, MediaSortTitleEnglish, MediaSortTitleEnglishDesc, MediaSortTitleNative, MediaSortTitleNativeDesc, MediaSortFormat, MediaSortFormatDesc, MediaSortStartDate, MediaSortStartDateDesc, MediaSortEndDate, MediaSortEndDateDesc, MediaSortScore, MediaSortScoreDesc, MediaSortPopularity, MediaSortPopularityDesc, MediaSortTrending, MediaSortTrendingDesc, MediaSortEpisodes, MediaSortEpisodesDesc, MediaSortDuration, MediaSortDurationDesc, MediaSortStatus, MediaSortStatusDesc, MediaSortUpdatedAt, MediaSortUpdatedAtDesc, MediaSortSearchMatch:
		return true
	}
	return false
}

func (e MediaSort) String() string {
	return string(e)
}

func (e *MediaSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaSort", str)
	}
	return nil
}

func (e MediaSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaSort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaSort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MediaStatus string

const (
	MediaStatusFinished       MediaStatus = "FINISHED"
	MediaStatusReleasing      MediaStatus = "RELEASING"
	MediaStatusNotYetReleased MediaStatus = "NOT_YET_RELEASED"
	MediaStatusCancelled      MediaStatus = "CANCELLED"
	MediaStatusHiatus         MediaStatus = "HIATUS"
)

var AllMediaStatus = []MediaStatus{
	MediaStatusFinished,
	MediaStatusReleasing,
	MediaStatusNotYetReleased,
	MediaStatusCancelled,
	MediaStatusHiatus,
}

func (e MediaStatus) IsValid() bool {
	switch e {
	case MediaStatusFinished, MediaStatusReleasing, MediaStatusNotYetReleased, MediaStatusCancelled, MediaStatusHiatus:
		return true
	}
	return false
}

func (e MediaStatus) String() string {
	return string(e)
}

func (e *MediaStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaStatus", str)
	}
	return nil
}

func (e MediaStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
